---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: {{ .Namespace }}
  generateName: {{ .GenerateName }}
  finalizers:
    - {{ .Finalizer }}
  labels:
    {{ .ComputeDomainLabelKey }}: {{ .ComputeDomainLabelValue }}
spec:
  selector:
    matchLabels:
      {{ .ComputeDomainLabelKey }}: {{ .ComputeDomainLabelValue }}
  template:
    metadata:
      labels:
        {{ .ComputeDomainLabelKey }}: {{ .ComputeDomainLabelValue }}
    spec:
      serviceAccountName: compute-domain-daemon-service-account
      nodeSelector:
        {{ .ComputeDomainLabelKey }}: {{ .ComputeDomainLabelValue }}
      containers:
      # Run the compute domain daemon
      - name: compute-domain-daemon
        image: {{ .ImageName }}
        imagePullPolicy: 
        command: ["bash", "-c", "echo 'fake daemon!' && sleep infinity"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        # Use runc: explicit "void"; otherwise we inherit "all".
        - name: NVIDIA_VISIBLE_DEVICES
          value: void
        resources:
          claims:
          - name: compute-domain-daemon
      # Repel all node taints.
      # See https://github.com/NVIDIA/k8s-dra-driver-gpu/issues/305
      tolerations:
        - operator: "Exists"
          effect: "NoSchedule"
        - operator: "Exists"
          effect: "NoExecute"
        - operator: "Exists"
          effect: "PreferNoSchedule"
      resourceClaims:
      - name: compute-domain-daemon
        resourceClaimTemplateName: {{ .ResourceClaimTemplateName }}
